# Generated by Django 4.0.2 on 2022-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_remove_solicitacao_resposta_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='contador',
            field=models.BooleanField(default=False),
        ),
    ]
